### PR TITLE
Reduce sklearn dependency in causalml

### PR DESCRIPTION
**Pull request by alexander-pv**
## Proposed changes

Hi!
Some people faced into binary incompatibility during package installation because causalml trees Cython code was linked to specific sklearn builds. Others got issues with numpy versions support. 

This PR  is aimed to resolve most of such issues.
In essence, Cython private code about trees was placed into the package with minimal changes instead of importing from scikit-learn.
Even though I initially didn't really like this idea, I came to the conclusion that it was necessary for the ease of the package use.

I think that code inside `causalml/inference/tree/_tree` should be updated rarely which basically makes sense in case of perfomance updates in scikit-learn trees codebase. Perhaps, these tree structures could be also reused in uplift trees. 

Other minor changes:
* Multiprocess Cython code compilation in `setup.py`
* A couple of additional details in `CONTRIBUTING.md`
* sklearn and numpy requirements were moved back to previous restrictions without upper bound: `numpy>=1.18.5, scikit-learn>=0.22.0`

Related issues: #579 #581 #619  #628  #671 #679 #680 #682 #684  

## Types of changes

What types of changes does your code introduce to **CausalML**?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/uber/causalml/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/uber/causalml)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc. This PR template is adopted from [appium](https://github.com/appium/appium).

### CODE REVIEW

**Comment by jeongyoonlee** [comment]
Thanks, @alexander-pv for the contribution - as always! 

One quick comment: Have you considered adding `scikit-learn/scikit-learn/tree` as a subtree ([ref](https://docs.github.com/en/get-started/using-git/about-git-subtree-merges#adding-a-new-repository-as-a-subtree)) instead of copying the code over?

**Comment by jeongyoonlee** [comment]
> Thanks, @alexander-pv for the contribution - as always!
> 
> One quick comment: Have you considered adding `scikit-learn/scikit-learn/tree` as a subtree ([ref](https://docs.github.com/en/get-started/using-git/about-git-subtree-merges#adding-a-new-repository-as-a-subtree)) instead of copying the code over?

There's no way to import only the tree subfolder as either a submodule or a subtree. :(
Let's take your approach - adding scikit-learn's tree code directly.

Can you fix the build error and resolve the conflict? Once it's cleared, I'll approve and merge it.

**Comment by alexander-pv** [comment]
> > Thanks, @alexander-pv for the contribution - as always!
> > One quick comment: Have you considered adding `scikit-learn/scikit-learn/tree` as a subtree ([ref](https://docs.github.com/en/get-started/using-git/about-git-subtree-merges#adding-a-new-repository-as-a-subtree)) instead of copying the code over?
> 
> There's no way to import only the tree subfolder as either a submodule or a subtree. :( Let's take your approach - adding scikit-learn's tree code directly.
> 
> Can you fix the build error and resolve the conflict? Once it's cleared, I'll approve and merge it.

Hi! I've learned about tree subfolders anyways and agree that neither subfodlers nor submodules could help to implement the initial idea. I will update the PR soon.

**Comment by alexander-pv** [comment]
It looks like everything is OK now.

**Review by jeongyoonlee — APPROVED** [review]
LGTM.

**Pull request merged**
