### PR TITLE
Causal trees interpretation example

### PR DESCRIPTION
**Pull request by alexander-pv**
## Proposed changes

Hi, I included `causal_trees_interpretation.ipynb` with an example of sklearn feature importance and shap for causal trees.
The related PR of causal trees support in shap: https://github.com/slundberg/shap/pull/2654

Additional minor changes:
* Makefile update to prevent cython from compilation errors in case of missing cython or sklearn.
* Basic Cython directives in `builder.pyx` to make cython compilation work as expected.

## Types of changes

What types of changes does your code introduce to **CausalML**?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/uber/causalml/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/uber/causalml)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc. This PR template is adopted from [appium](https://github.com/appium/appium).

### CODE REVIEW

**Review by jeongyoonlee — APPROVED** [review]
LGTM. Thanks!

**Comment by himanData** [comment]
Hi @alexander-pv 
Thanks for the update. It seems there are some circular module dependencies in the file. I am getting 
```Cannot import name 'plot_dist_tree_leaves_valuess' from causalml.inferenece.tree....```

**Comment by alexander-pv** [comment]
Hi, @himanData,
That's strange, I can't get the error in this [notebook](https://github.com/uber/causalml/blob/master/examples/causal_trees_interpretation.ipynb)
Actually, row `from causalml.inference.tree import plot_dist_tree_leaves_values, get_tree_leaves_mask` is just a copy from the previous notebook about causal trees and can be ommited.

**Comment by himanData** [comment]
Thank you. I actually get the same error for `CasualRandomForestRegressor`
```Cannot import name 'CasualRandomForestRegressor' from causalml.inferenece.tree....```

**Comment by alexander-pv** [comment]
It seems that you just mistyped names. Please, check the names in the notebook.

You can also check whether your causalml package is up-to-date or not by looking into `<your path to installed python packages>causalml/inference/tree/__init__.py`.

**Comment by himanData** [comment]
I am using your .ipynb file. 
The text I typed here I just typed it myself so maybe I mistyped it as I am using GitHub on a different laptop so I couldn't just copy and paste it. 

Also, I did update the causalml and mine is the same version as the one shown on your notebook

**Comment by alexander-pv** [comment]
I see. Did you install the package from source?

**Comment by himanData** [comment]
I did it by !pip install casualml within the notebook

**Pull request merged**
