### PR TITLE
Fix unreproducible UpliftRandomForestClassifier

### PR DESCRIPTION
**Pull request by RuslanTs**
## Proposed changes
issue #275

UpliftRandomForestClassifier doesn't give the same results when runs with the same data and the same params (seed fixed). Now it's reproducible (wasn't fix random seed in bootstrap).

## Types of changes

What types of changes does your code introduce to **CausalML**?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/uber/causalml/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/uber/causalml)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc. This PR template is adopted from [appium](https://github.com/appium/appium).

### CODE REVIEW

**Comment by paullo0106** [comment]
Looks good, thanks for the contribution!

Just to confirm, do we also need to set `random.seed` in [growDecisionTreeFrom()](https://github.com/uber/causalml/blob/master/causalml/inference/tree/models.py#L941) when we randomly select a few columns? Or this should be handle by the existing random.seed invoked earlier (?) in `fit()` and `bootstrap()`

**Review by ppstacy — APPROVED** [review]

**Comment by RuslanTs** [comment]
> Looks good, thanks for the contribution!
> 
> Just to confirm, do we also need to set `random.seed` in [growDecisionTreeFrom()](https://github.com/uber/causalml/blob/master/causalml/inference/tree/models.py#L941) when we randomly select a few columns? Or this should be handle by the existing random.seed invoked earlier (?) in `fit()` and `bootstrap()`

Yes, you right! I fixed this in the new commit.

**Review by paullo0106 — APPROVED** [review]
Thanks!

**Comment by paullo0106** [comment]
`Travis CI - Pull Request Failing after 38m — Build Failed` ->  maybe we can rerun the checks and merge

**Comment by RuslanTs** [comment]
Tbh, test cases are quite strange, because in sum by all users a model could be worse than random.
The goal of uplift-modeling is to find some portion of users to treatment, where treatment should be better than it's absence.
I modified the test a bit to pass, but I'm not sure what test cases should be here

**Comment by RuslanTs** [comment]
Seems I cracked bootstrap and my approach is bad. It has to be the completely different realization of bootstrap (like in sklearn, as an example)

**Comment by paullo0106** [comment]
> Seems I cracked bootstrap and my approach is bad. It has to be the completely different realization of bootstrap (like in sklearn, as an example)

@RuslanTs can you clarify this? are there more changes you'd suggest and add to the PR? Thanks

**Comment by RuslanTs** [comment]
It should be a different approach to deal with bootstrap - to make UpliftRandomForestClassifier reproducible. 
My fixes do it reproducible, but bootstrap doesn't work in this case.

**Pull request closed without merging**
