### PR TITLE
fix issue filter method failure with NaNs in the data issue #348, add…

### PR DESCRIPTION
**Pull request by manojbalaji1**
…  null_impute using sklearn SimpleImputer

## Proposed changes

NaNs present in the data caused pd.qcut at https://github.com/uber/causalml/blob/master/causalml/feature_selection/filters.py#L341 to return np.nan as NaN values don't fall in any specified bin range. This caused issue since x_bins.max() returned np.nan which caused error at line https://github.com/uber/causalml/blob/master/causalml/feature_selection/filters.py#L344

## Types of changes

What types of changes does your code introduce to **CausalML**?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/uber/causalml/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/uber/causalml)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

First to fix the issue raised in #348 ,  changed the code at https://github.com/uber/causalml/blob/master/causalml/feature_selection/filters.py#L344 from x_bins.max() to np.nanmax(x_bins).astype(int) which will no more return np.nan as max value since it picks max value from given input ignoring np.nan.
Also introduced NaN imputation. As suggested by the author in the aforementioned issue #348, Added a way to pass null_impute argument to impute data. Used SimpleImputer from sklearn to do the same

### CODE REVIEW

**Review by paullo0106 — APPROVED** [review]
LGTM, thanks!

**Comment by manojbalaji1** [comment]
Thanks @paullo0106 !

**Comment by bponedel** [comment]
The imputation feature is great but is the resolution of the nan error in the `.max()` really the desired behavior? This will ignore rows of the data that have nans in that column silently and will not raise any error. Would it not be more desirable to raise an error or at least a warning? Just a thought.

Could also link the issue to the PR in the "linked issues" section so that they are associated. 👍

**Comment by manojbalaji1** [comment]
@bponedel 
Shouldn't it be so? Let's say in real life, as a data scientist, If I give you data with nulls, you can either ignore the nulls and go ahead or impute nulls and go ahead. I agree that we should add some warning stating "nulls present in data, please use null_impute to impute null else will be ignored".
@paullo0106 what's your opinion on this?

**Comment by bponedel** [comment]
I see your point and I certainly defer to people more knowledgable about these filter methods and a warning is good.
I guess I was thinking that if the method really doesn't work as intended when rows are skipped (i.e. if it has the chance to misrank the feature) then it might be better to error in the presence of NaNs unless an option is passed to explicitly go forward skipping NaNs. So something like: error if NaNs are present unless an imute arg or `null_impute ="skip"` is passed. The thing that worries me is that the warnings could be too quiet and someone who is new to the method misses it.

**Comment by paullo0106** [comment]
@t-tte adding you to the reviewer list as you were one of the authors of Feature Selection methods with @zhenyuz0500 and @yungmsh - your input would be very helpful here!

@manojbalaji1 on a side note, if we are pushing this through, we might also need to replace line 367 `'misc': 'number_of_bins: {}'.format(min(n_bins, x_bin.max()+1))` with your `x_bin.nanmax()` changes

**Comment by t-tte** [comment]
Thanks for the heads up @paullo0106. If there are NaNs present in the features, I think it's safest to raise the following error:

> NaNs present in features. Please specify null_impute argument or deal with NaNs before using the method.

We don't currently have a good idea of how skipping rows (or, for that matter, different imputation methods) influence the performance of the filter approach, so it makes sense to be conservative. I can also imagine that many data scientists will want to use different imputation methods than what are available in SimpleImputer.

**Comment by manojbalaji1** [comment]
@t-tte in that case, we can raise error as mentioned and provide null_impute as an optional variable if they want to use imputation, or skip. This way they have an option to impute by themselves and then provide the dataframe, skip or use the options mentioned in this PR(the one that uses simpkeimputer). What do you say?

**Comment by t-tte** [comment]
This sounds good to me @manojbalaji1 👍

**Comment by zhenyuz0500** [comment]
Thanks for making this fix! 
Adding an error message and providing x_bin.nanmax() as an option to fix this issue sounds good to me. 
It might influence the performance of the function, depending on the proportion of missing value and the mechanism. Therefore, in the future, considering advanced imputation methods, such as creating another binary row indicating if a feature value is missing can be helpful in severe missing value scenario.

**Comment by paullo0106** [comment]
Thanks for all the great discussions! Seems like we are aligned to merge this. For other potential enhancements, we can add them later in another PR.

**Pull request merged**
