### PR TITLE
Add with_std, with_counts to create_table_one

### PR DESCRIPTION
**Pull request by lee-junseok**
## Proposed changes

A auxiliary function [create_table_one](https://github.com/uber/causalml/blob/750e84e4916e6ec1f364bd30d5504f9b0e437f93/causalml/match.py#L34) currently generates a table of mean values in a string format of "{:.2f} ({:.2f})".format(x.mean(), x.std()) and a user cannot use the mean values directly from the output table along with SMD calculated.

Issue: https://github.com/uber/causalml/issues/747

## Types of changes

What types of changes does your code introduce to **CausalML**?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/uber/causalml/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/uber/causalml)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc. This PR template is adopted from [appium](https://github.com/appium/appium).

### CODE REVIEW

**Comment by jeongyoonlee** [comment]
Thanks for your contribution, @lee-junseok. Currently, [the linting test](https://github.com/uber/causalml/actions/runs/8395178308/job/22993901010?pr=748) is failing. Can you run the latest `black` and update the PR? Thanks.

**Comment by paullo0106** [comment]
@lee-junseok you can find the details in the [failed log here](https://github.com/uber/causalml/actions/runs/8395178308/job/22993901010?pr=748). To fix the formatting error with `black`, you can check our [contribution guide](https://github.com/uber/causalml/blob/master/CONTRIBUTING.md). Thanks

```
# move to the top directory of the causalml repository
$ cd causalml 
$ pip install -U black
$ black . 
```

**Comment by lee-junseok** [comment]
Sorry for the delay. Addressed the issue

**Review by jeongyoonlee — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
