### PR TITLE
reorder notebook

### PR DESCRIPTION
**Pull request by vincewu51**
## Proposed changes

This is to solve [issue664](https://github.com/uber/causalml/issues/664). 
1. Re-ordered all notebooks based on submission time.
2. Re-run all notebooks to make sure they work and make minor changes. (except for 014, which results in kernel dying in my local. I'll start another PR to solve the issue). 

## Types of changes

What types of changes does your code introduce to **CausalML**?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] I have read the [CONTRIBUTING](https://github.com/uber/causalml/blob/master/CONTRIBUTING.md) doc
- [X] I have signed the [CLA](https://cla-assistant.io/uber/causalml)
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc. This PR template is adopted from [appium](https://github.com/appium/appium).

### CODE REVIEW

**Comment by jeongyoonlee** [comment]
@vincewu51, this PR has different SHAs for previous commits, which conflicts with the `master`'s commits. To get a clean rebase, you can use commands as follows:
```
git checkout master
git pull
git checkout [your branch]
git rebase origin/master
git push origin [your branch] --force
```

**Comment by vincewu51** [comment]
> @vincewu51, this PR has different SHAs for previous commits, which conflicts with the `master`'s commits. To get a clean rebase, you can use commands as follows:
> 
> ```
> git checkout master
> git pull
> git checkout [your branch]
> git rebase origin/master
> git push origin [your branch] --force
> ```

Thanks @jeongyoonlee, I rebased following the commandas.

**Comment by jeongyoonlee** [comment]
The order of the notebooks might change later, and adding indices to the file names might lead to the renaming of the multiple notebook files.

Instead, I think it's better to update [`docs/examples.rst`](https://causalml.readthedocs.io/en/latest/examples.html) and [`README.md`s Quick Start section](https://github.com/uber/causalml#quick-start) to provide guides to go through example notebooks.

**Comment by vincewu51** [comment]
Ok, I'll remove the indices and add guidance in the document instead.

**Comment by vincewu51** [comment]
The conflict is complicated to resolve after [697](https://github.com/uber/causalml/pull/697) and others. It's safer to for me to open a new PR. I'll close this one.

**Pull request closed without merging**
