### PR TITLE
Add IIA and value optimization related documentation

### LINKED ISSUE #192: IIA Integration: Documentation
Add documentation for IIA code to About, Methodology and README.

### PR DESCRIPTION
**Pull request by t-tte**
## Proposed changes

- Add IIA related documentation
- Add value optimization related documentation
- Add refs
- Closes #192 

## Types of changes

What types of changes does your code introduce to **CausalML**?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/uber/causalml/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/uber/causalml)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc. This PR template is adopted from [appium](https://github.com/appium/appium).

### CODE REVIEW

**Comment by t-tte** [comment]
For some reason, I was not able to add @yungmsh or @zhenyuz0500 as reviewers.

**Comment by t-tte** [comment]
> [CLA assistant check](https://cla-assistant.io/uber/causalml?pullRequest=264) 
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/uber/causalml?pullRequest=264) before we can accept your contribution.
> 
> **t-tte** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/uber/causalml?pullRequest=264) it.

It seems like I got this because the email associated with the commit was incorrect (fixed now). I've of course signed the CLA in the past.

**Comment by jeongyoonlee** [comment]
Thanks @t-tte! Could you add a brief intro about value optimization methods to README.md as well? Otherwise, LGTM!

**Review by toanoyx — APPROVED** [review]

**Review by jeongyoonlee — APPROVED** [review]
Let's merge this one, and open a new one for README.md later. Thanks!

**Pull request merged**
